import { readFileSync, existsSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BLUEPRINTS = {
  'alert-stack': 'alert-stack.html',
  'breadcrumb-bar': 'breadcrumb-bar.html',
  'card-grid': 'card-grid.html',
  'footer-simple': 'footer-simple.html',
  'form-contact': 'form-contact.html',
  'form-login': 'form-login.html',
  'hero-section': 'hero-section.html',
  'layout-dashboard': 'layout-dashboard.html',
  modal: 'modal.html',
  'navbar-header': 'navbar-header.html',
  'pagination-bar': 'pagination-bar.html',
  'search-field': 'search-field.html',
  'sidebar-layout': 'sidebar-layout.html',
  'table-responsive': 'table-responsive.html',
};

export function listBlueprints() {
  return Object.keys(BLUEPRINTS);
}

export function emitBlueprint(id, { output } = {}) {
  const file = BLUEPRINTS[id];
  if (!file) return { ok: false, error: `Unknown blueprint "${id}". Try: ${listBlueprints().join(', ')}` };
  const path = join(__dirname, 'blueprints', file);
  if (!existsSync(path)) return { ok: false, error: `Missing template: ${path}` };
  const body = readFileSync(path, 'utf-8');
  const banner = `<!-- Generated by velinstyle blueprint ${id} — VelinStyle tokens: --velin-color-*, --velin-space-*, --velin-radius-* -->\n`;
  const out = banner + body;
  if (output) {
    writeFileSync(output, out, 'utf-8');
    return { ok: true, path: output };
  }
  return { ok: true, text: out };
}
