/**
 * Opinionated scaffolds with validated VelinStyle classes only.
 */
import { existsSync, mkdirSync, writeFileSync, copyFileSync, cpSync } from 'fs';
import { join, resolve } from 'path';
import { validateBlueprintHtml, loadKnownCssClasses } from './blueprint.js';

export const CREATE_KINDS = ['landing', 'dashboard', 'docs', 'auth'];

function bootScript(vendorPath, tags) {
  const list = tags.map((t) => `'${t}'`).join(', ');
  return `  <script type="module">
    async function boot() {
      try {
        const { bootFromDOM } = await import('@birdapi/velinstyle/runtime');
        await bootFromDOM(document, {
          attributes: true,
          tags: [${list}],
        });
        return;
      } catch {
        /* offline / vendor install — no package resolver */
      }
      await import('./${vendorPath}/velinstyle-components.min.js');
    }
    boot();
  </script>`;
}

function head({ title, theme, vendorPath, intent, goals }) {
  const sprite = `${vendorPath}/velin-icons.svg`;
  const goalsJson = JSON.stringify(goals);
  return `<!DOCTYPE html>
<html lang="en" data-velin-theme="${theme}" data-velin-reveal-auto>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="velin-icon-sprite" content="${sprite}">
  <title>${title}</title>
  <link rel="stylesheet" href="${vendorPath}/velinstyle.min.css">
  <link rel="stylesheet" href="${vendorPath}/themes/${theme}.min.css">
  <script type="application/vnd.velinstyle.meta+json" id="velin-meta">
{
  "version": "1.2.0",
  "page": {
    "intent": "${intent}",
    "title": "${title}",
    "goals": ${goalsJson}
  }
}
  </script>
</head>`;
}

function landingHtml({ theme, vendorPath }) {
  return `${head({ title: 'VelinStyle landing', theme, vendorPath, intent: 'page:landing', goals: ['marketing-landing'] })}
<body>
  <a class="velin-skip-link" href="#main">Skip to main content</a>
  <header class="velin-container velin-flex velin-flex--justify-between velin-flex--items-center velin-flex--wrap velin-gap-3 velin-py-4" role="banner">
    <a class="velin-text-lg velin-font-bold velin-no-underline velin-text-inherit" href="#hero">Brand</a>
    <nav class="velin-flex velin-flex--gap-2 velin-flex--wrap" aria-label="Primary">
      <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#features">Features</a>
      <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#contact">Contact</a>
      <a class="velin-btn velin-btn--primary velin-btn--sm" href="#contact">Get started</a>
    </nav>
    <velin-theme-toggle themes-base="${vendorPath}/themes/"></velin-theme-toggle>
  </header>

  <main id="main">
    <section class="velin-container velin-py-10" id="hero" data-velin-section="hero" aria-labelledby="hero-title">
      <h1 id="hero-title" class="velin-text-4xl velin-font-bold velin-mbe-4">Build accessible UIs faster</h1>
      <p class="velin-text-lg velin-text-muted velin-mbe-6">Generated by <code>velinstyle create landing</code> — only classes that exist in VelinStyle CSS.</p>
      <div class="velin-flex velin-flex--gap-3 velin-flex--wrap">
        <a class="velin-btn velin-btn--primary" href="#contact">Primary CTA</a>
        <a class="velin-btn velin-btn--outline" href="#features">Secondary</a>
      </div>
    </section>

    <section class="velin-container velin-py-8" id="features" aria-labelledby="features-title">
      <h2 id="features-title" class="velin-text-3xl velin-font-bold velin-mbe-6">Features</h2>
      <div class="velin-grid velin-grid--auto-fit velin-gap-4">
        <article class="velin-card"><div class="velin-card__body"><h3 class="velin-card__title">Tokens</h3><p class="velin-card__text">OKLCH themes</p></div></article>
        <article class="velin-card"><div class="velin-card__body"><h3 class="velin-card__title">A11y</h3><p class="velin-card__text">Contracts + scanner</p></div></article>
        <article class="velin-card"><div class="velin-card__body"><h3 class="velin-card__title">CLI</h3><p class="velin-card__text">plan · review · scan · check</p></div></article>
      </div>
    </section>

    <section class="velin-container velin-py-8" id="contact" aria-labelledby="contact-title">
      <h2 id="contact-title" class="velin-text-3xl velin-font-bold velin-mbe-4">Contact</h2>
      <form class="velin-flex velin-flex--col velin-gap-3 velin-max-w-md" novalidate>
        <velin-form-summary></velin-form-summary>
        <label class="velin-flex velin-flex--col velin-gap-1" for="landing-email">
          <span>Email</span>
          <input id="landing-email" class="velin-input" type="email" name="email" required autocomplete="email">
        </label>
        <label class="velin-flex velin-flex--col velin-gap-1" for="landing-message">
          <span>Message</span>
          <textarea id="landing-message" class="velin-input" name="message" rows="4" required></textarea>
        </label>
        <button type="submit" class="velin-btn velin-btn--primary">Send</button>
      </form>
    </section>
  </main>

  <footer class="velin-container velin-py-6 velin-border-block-start velin-text-sm velin-text-muted" role="contentinfo">
    <p>Built with VelinStyle · run <code>velinstyle serve</code> to preview</p>
  </footer>

${bootScript(vendorPath, ['velin-theme-toggle', 'velin-form-summary'])}
</body>
</html>
`;
}

function dashboardHtml({ theme, vendorPath }) {
  const today = new Date().toISOString().slice(0, 10);
  return `${head({ title: 'VelinStyle dashboard', theme, vendorPath, intent: 'page:dashboard', goals: ['admin-shell'] })}
<body>
  <a class="velin-skip-link" href="#main">Skip to main content</a>
  <div class="velin-app-shell">
    <aside class="velin-app-shell__nav velin-p-4 velin-border-inline-end" aria-label="App">
      <p class="velin-text-lg velin-font-bold velin-mbe-4">Console</p>
      <nav class="velin-flex velin-flex--col velin-gap-2" aria-label="Sidebar">
        <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#main">Overview</a>
        <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#uploads">Uploads</a>
        <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#calendar">Calendar</a>
      </nav>
      <div class="velin-mbs-6" id="calendar">
        <h2 class="velin-text-sm velin-font-bold velin-mbe-2">Calendar</h2>
        <velin-calendar label="Pick a day" value="${today}"></velin-calendar>
      </div>
    </aside>
    <div class="velin-app-shell__body">
      <header class="velin-flex velin-flex--justify-between velin-flex--items-center velin-gap-3 velin-p-4 velin-border-block-end" role="banner">
        <h1 class="velin-text-xl velin-font-bold">Operations</h1>
        <velin-theme-toggle themes-base="${vendorPath}/themes/"></velin-theme-toggle>
      </header>
      <main id="main" class="velin-app-shell__content velin-p-6">
        <p class="velin-text-muted velin-mbe-4">Generated by <code>velinstyle create dashboard</code>. Double-click a cell to edit.</p>
        <label class="velin-flex velin-flex--col velin-gap-1 velin-mbe-3 velin-max-w-md" for="dash-filter">
          <span>Filter rows</span>
          <input id="dash-filter" class="velin-input" type="search" autocomplete="off">
        </label>
        <velin-data-table label="Team tasks" page-size="5" filter-input="#dash-filter" editable empty-text="No tasks">
          <table>
            <caption class="velin-sr-only">Team tasks</caption>
            <thead>
              <tr>
                <th data-sort="text">Task</th>
                <th data-sort="text">Owner</th>
                <th data-sort="text">Status</th>
              </tr>
            </thead>
            <tbody>
              <tr><td data-editable>Ship trust gates</td><td data-editable>Ada</td><td data-editable>Done</td></tr>
              <tr><td data-editable>Wire calendar</td><td data-editable>Lin</td><td data-editable>In review</td></tr>
              <tr><td data-editable>Upload dropzone</td><td data-editable>Kai</td><td data-editable>Todo</td></tr>
              <tr><td data-editable>Docs shell</td><td data-editable>Sam</td><td data-editable>Todo</td></tr>
              <tr><td data-editable>Auth form</td><td data-editable>Rio</td><td data-editable>Done</td></tr>
              <tr><td data-editable>SARIF check</td><td data-editable>Ada</td><td data-editable>Done</td></tr>
            </tbody>
          </table>
        </velin-data-table>

        <section class="velin-mbs-8" id="uploads" aria-labelledby="upload-title">
          <h2 id="upload-title" class="velin-text-2xl velin-font-bold velin-mbe-3">Uploads</h2>
          <velin-file-dropzone label="Project files" accept=".pdf,.png,.jpg,.csv" multiple></velin-file-dropzone>
        </section>
      </main>
    </div>
  </div>
${bootScript(vendorPath, ['velin-theme-toggle', 'velin-data-table', 'velin-calendar', 'velin-file-dropzone'])}
</body>
</html>
`;
}

function docsHtml({ theme, vendorPath }) {
  return `${head({ title: 'VelinStyle docs', theme, vendorPath, intent: 'page:docs', goals: ['docs-shell'] })}
<body>
  <a class="velin-skip-link" href="#main">Skip to main content</a>
  <header class="velin-container velin-flex velin-flex--justify-between velin-flex--items-center velin-py-4" role="banner">
    <a class="velin-text-lg velin-font-bold velin-no-underline velin-text-inherit" href="#main">Docs</a>
    <velin-theme-toggle themes-base="${vendorPath}/themes/"></velin-theme-toggle>
  </header>
  <div class="velin-container velin-flex velin-flex--wrap velin-gap-6 velin-py-6">
    <nav class="velin-docs-nav velin-flex velin-flex--col velin-gap-2" aria-label="Docs">
      <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#intro">Introduction</a>
      <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#install">Install</a>
      <a class="velin-btn velin-btn--ghost velin-btn--sm" href="#check">Check gate</a>
    </nav>
    <aside class="velin-toc velin-text-sm velin-text-muted" aria-label="On this page">
      <p class="velin-font-bold velin-mbe-2">On this page</p>
      <ul class="velin-stack">
        <li><a href="#intro">Introduction</a></li>
        <li><a href="#install">Install</a></li>
        <li><a href="#check">Check gate</a></li>
      </ul>
    </aside>
    <main id="main" class="velin-docs-main">
      <h1 id="intro" class="velin-text-3xl velin-font-bold velin-mbe-4">Introduction</h1>
      <p class="velin-mbe-4">This docs shell is generated by <code>velinstyle create docs</code>. Use it for guides and API notes.</p>
      <h2 id="install" class="velin-text-2xl velin-font-bold velin-mbe-3">Install</h2>
      <velin-code-block language="bash">npm install @birdapi/velinstyle
npx velinstyle create docs ./docs-site</velin-code-block>
      <h2 id="check" class="velin-text-2xl velin-font-bold velin-mbs-6 velin-mbe-3">Check gate</h2>
      <p class="velin-mbe-3">Run the quality gate before you ship:</p>
      <velin-code-block language="bash">npx velinstyle check . --json</velin-code-block>
    </main>
  </div>
${bootScript(vendorPath, ['velin-theme-toggle', 'velin-code-block'])}
</body>
</html>
`;
}

function authHtml({ theme, vendorPath }) {
  return `${head({ title: 'VelinStyle sign in', theme, vendorPath, intent: 'page:auth', goals: ['auth-login'] })}
<body>
  <a class="velin-skip-link" href="#main">Skip to main content</a>
  <main id="main" class="velin-container velin-py-10 velin-max-w-md">
    <h1 class="velin-text-3xl velin-font-bold velin-mbe-2">Sign in</h1>
    <p class="velin-text-muted velin-mbe-6">Generated by <code>velinstyle create auth</code>.</p>
    <form class="velin-flex velin-flex--col velin-gap-3" novalidate>
      <velin-form-summary></velin-form-summary>
      <label class="velin-flex velin-flex--col velin-gap-1" for="auth-email">
        <span>Email</span>
        <input id="auth-email" class="velin-input" type="email" name="email" required autocomplete="username">
      </label>
      <label class="velin-flex velin-flex--col velin-gap-1" for="auth-password">
        <span>Password</span>
        <input id="auth-password" class="velin-input" type="password" name="password" required autocomplete="current-password">
      </label>
      <button type="submit" class="velin-btn velin-btn--primary">Continue</button>
    </form>
    <p class="velin-text-sm velin-text-muted velin-mbs-4"><a href="#">Forgot password</a></p>
  </main>
${bootScript(vendorPath, ['velin-form-summary'])}
</body>
</html>
`;
}

const HTML_BY_KIND = {
  landing: landingHtml,
  dashboard: dashboardHtml,
  docs: docsHtml,
  auth: authHtml,
};

function copyVendor(pkgRoot, destVendor) {
  const dist = join(pkgRoot, 'dist');
  if (!existsSync(join(dist, 'velinstyle.min.css'))) {
    return { ok: false, missing: dist };
  }
  mkdirSync(destVendor, { recursive: true });
  const files = ['velinstyle.min.css', 'velinstyle-components.min.js', 'velin-icons.svg'];
  const copied = [];
  for (const f of files) {
    const src = join(dist, f);
    if (existsSync(src)) {
      copyFileSync(src, join(destVendor, f));
      copied.push(f);
    }
  }
  const themesSrc = join(dist, 'themes');
  if (existsSync(themesSrc)) {
    cpSync(themesSrc, join(destVendor, 'themes'), { recursive: true });
    copied.push('themes/');
  }
  const docsSrc = join(pkgRoot, 'docs/generated/components');
  const mini = [
    'velin-toast.md',
    'velin-data-table.md',
    'velin-calendar.md',
    'velin-file-dropzone.md',
    'velin-stepper.md',
    'velin-search.md',
    'velin-form-summary.md',
    'velin-theme-toggle.md',
    'velin-rating.md',
  ];
  if (existsSync(docsSrc)) {
    const destDocs = join(destVendor, 'docs');
    mkdirSync(destDocs, { recursive: true });
    const indexLines = [
      '# VelinStyle WC mini-docs (offline)',
      '',
      'Copied with `velinstyle create`. Full set: framework `docs/generated/components/`.',
      'CLI: `velinstyle wc api <tag>` (e.g. `velin-toast`).',
      '',
    ];
    for (const f of mini) {
      const src = join(docsSrc, f);
      if (existsSync(src)) {
        copyFileSync(src, join(destDocs, f));
        copied.push(`docs/${f}`);
        indexLines.push(`- [${f.replace('.md', '')}](./${f})`);
      }
    }
    writeFileSync(join(destDocs, 'README.md'), `${indexLines.join('\n')}\n`, 'utf-8');
    copied.push('docs/README.md');
  }
  return { ok: copied.includes('velinstyle.min.css'), copied, destVendor };
}

/**
 * @param {{ kind: string, dir: string, pkgRoot: string, theme?: string, copyAssets?: boolean }} opts
 */
export function createProject(opts) {
  const kind = opts.kind || 'landing';
  if (!CREATE_KINDS.includes(kind)) {
    return { ok: false, error: `Unknown create kind "${kind}". Use: ${CREATE_KINDS.join('|')}` };
  }
  const dir = resolve(opts.dir || kind);
  const theme = opts.theme || (kind === 'dashboard' ? 'forest' : 'earth');
  const vendorRel = 'vendor/velinstyle';
  mkdirSync(dir, { recursive: true });

  let vendorResult = null;
  if (opts.copyAssets !== false) {
    vendorResult = copyVendor(opts.pkgRoot, join(dir, vendorRel));
    if (!vendorResult.ok) {
      return {
        ok: false,
        error: `Framework dist/ not found at ${vendorResult.missing}. Build the framework or copy dist into ${vendorRel} manually.`,
      };
    }
  }

  let html = HTML_BY_KIND[kind]({ theme, vendorPath: vendorRel });
  const check = validateBlueprintHtml(html, loadKnownCssClasses());
  if (!check.ok) {
    return { ok: false, error: `Scaffold emitted unknown classes: ${check.missing.join(', ')}` };
  }

  const indexPath = join(dir, 'index.html');
  writeFileSync(indexPath, html, 'utf-8');

  const readme = `# VelinStyle ${kind}

Created with \`velinstyle create ${kind}\`.

\`\`\`bash
velinstyle serve .
velinstyle check .
\`\`\`

Assets: \`${vendorRel}/\` · Theme: \`${theme}\`.
Offline WC notes: \`${vendorRel}/docs/\` · API: \`velinstyle wc api velin-toast\`.
Prefer \`import { bootFromDOM } from '@birdapi/velinstyle/runtime'\` in apps with the npm package.
`;
  writeFileSync(join(dir, 'README.md'), readme, 'utf-8');

  return {
    ok: true,
    kind,
    dir,
    indexPath,
    vendor: join(dir, vendorRel),
    vendorRel,
    theme,
    vendorCopied: vendorResult?.copied || [],
  };
}

/** @deprecated use createProject({ kind: 'landing', ... }) */
export function createLanding(opts) {
  return createProject({ ...opts, kind: 'landing' });
}
