/**
 * Prompt-based scaffolding: map natural language to VelinStyle blueprint composition.
 */
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { emitBlueprint } from './blueprint.js';
import { auditHtml, suggestFromIssues } from './layout-audit.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const RECIPES_PATH = join(__dirname, 'scaffold-recipes.json');

function loadRecipes() {
  return JSON.parse(readFileSync(RECIPES_PATH, 'utf-8'));
}

/**
 * @param {string} prompt
 */
export function parseIntent(prompt) {
  const recipes = loadRecipes();
  const lower = prompt.toLowerCase();
  let best = { id: recipes.fallback.intent, confidence: recipes.fallback.confidence, score: 0 };

  for (const [id, def] of Object.entries(recipes.intents)) {
    let score = 0;
    for (const kw of def.keywords) {
      if (lower.includes(kw.toLowerCase())) score += kw.length;
    }
    if (score > best.score) {
      best = { id, confidence: def.confidence || 'medium', score };
    }
  }

  return { id: best.id, confidence: best.score > 0 ? best.confidence : 'low' };
}

/**
 * @param {string} prompt
 */
export function extractSlots(prompt) {
  const recipes = loadRecipes();
  const lower = prompt.toLowerCase();
  const slots = {
    brand: 'Brand',
    title: 'Welcome',
    cta: 'Get started',
    columns: 3,
  };

  const brandMatch = prompt.match(/(?:brand|logo|marke)\s*[:\-]?\s*["']?([^"'\n,]+)/i);
  if (brandMatch) slots.brand = brandMatch[1].trim();

  const titleMatch = prompt.match(/(?:title|titel|heading)\s*[:\-]?\s*["']?([^"'\n]+)/i);
  if (titleMatch) slots.title = titleMatch[1].trim();

  const colMatch = lower.match(/(\d+)\s*(?:spalten|columns|cols|karten|cards)/);
  if (colMatch) slots.columns = Math.min(12, Math.max(1, parseInt(colMatch[1], 10)));

  for (const [slot, keys] of Object.entries(recipes.slots || {})) {
    if (keys.some((k) => lower.includes(k)) && slot === 'cta') {
      slots.cta = 'Get started';
    }
  }

  if (/suche|search/i.test(prompt)) slots.includeSearch = true;

  return slots;
}

/**
 * @param {string} intentId
 * @param {{ prompt?: string, slots?: object }} options
 */
export function resolveBlueprints(intentId, options = {}) {
  const recipes = loadRecipes();
  const def = recipes.intents[intentId] || recipes.intents[recipes.fallback.intent];
  const ids = [...def.blueprints];

  const lower = (options.prompt || '').toLowerCase();
  if (def.optionalIf) {
    for (const [key, bps] of Object.entries(def.optionalIf)) {
      if (lower.includes(key)) ids.push(...bps);
    }
  }
  if (options.slots?.includeSearch && intentId === 'navbar' && !ids.includes('search-field')) {
    ids.push('search-field');
  }

  return [...new Set(ids)];
}

function applySlots(html, slots) {
  let out = html;
  out = out.replace(/\bBrand\b/g, slots.brand);
  out = out.replace(/Card one/gi, `${slots.title} — 1`);
  out = out.replace(/Welcome/gi, slots.title);
  out = out.replace(/Get started/gi, slots.cta);
  return out;
}

/**
 * @param {string} prompt
 * @param {{ pkgRoot?: string }} options
 */
export function scaffoldFromPrompt(prompt, options = {}) {
  if (!prompt || !prompt.trim()) {
    return { ok: false, error: 'Prompt is required.' };
  }

  const intent = parseIntent(prompt);
  const slots = extractSlots(prompt);
  const blueprintIds = resolveBlueprints(intent.id, { prompt, slots });

  const parts = [];
  for (const id of blueprintIds) {
    const r = emitBlueprint(id, {});
    if (!r.ok) {
      return { ok: false, error: r.error };
    }
    parts.push(r.text);
  }

  let html = parts.join('\n\n');
  html = applySlots(html, slots);

  const banner =
    `<!-- Generated by velinstyle scaffold (0.8.0) — intent: ${intent.id}, confidence: ${intent.confidence} -->\n` +
    `<!-- Blueprints: ${blueprintIds.join(', ')} — run: velinstyle layout suggest & velinstyle scan -->\n`;

  const fullHtml = banner + html;
  const issues = auditHtml(fullHtml);
  const responsiveHints = suggestFromIssues(issues);

  return {
    ok: true,
    intent: intent.id,
    confidence: intent.confidence,
    blueprints: blueprintIds,
    html: fullHtml,
    slots,
    responsiveHints,
    nextSteps: ['velinstyle layout suggest <file>', 'velinstyle scan <file>'],
  };
}

export function listIntents() {
  const recipes = loadRecipes();
  return Object.entries(recipes.intents).map(([id, def]) => ({
    id,
    keywords: def.keywords,
    blueprints: def.blueprints,
    confidence: def.confidence,
  }));
}
