/**
 * Minimal Markdown helpers for doc generation (stable sort, escaping).
 */

export function escapeCell(s) {
  return String(s ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ');
}

export function heading(level, text) {
  const n = Math.min(6, Math.max(1, level));
  return `${'#'.repeat(n)} ${text}\n`;
}

export function table(headers, rows) {
  const h = headers.map(escapeCell);
  const lines = [
    `| ${h.join(' | ')} |`,
    `| ${h.map(() => '---').join(' | ')} |`,
  ];
  for (const row of rows) {
    lines.push(`| ${row.map(escapeCell).join(' | ')} |`);
  }
  return `${lines.join('\n')}\n`;
}

export function bulletList(items) {
  if (!items.length) return '_None._\n';
  return `${items.map((i) => `- ${i}`).join('\n')}\n`;
}

export function codeBlock(lang, code) {
  return `\`\`\`${lang}\n${code}\n\`\`\`\n`;
}

export function banner(source) {
  return `<!-- Auto-generated by \`velinstyle docs generate\`. Do not edit. Source: ${source} -->\n\n`;
}

export function sortByKey(arr, key) {
  return [...arr].sort((a, b) => String(a[key]).localeCompare(String(b[key])));
}
