/**
 * AUTO-GENERATED — run: node scripts/generate-component-loaders.mjs
 */
export const COMPONENT_LOADERS = {
  'velin-accordion': () => import('../velin-accordion.js'),
  'velin-announcer': () => import('../velin-announcer.js'),
  'velin-bottom-nav': () => import('../velin-bottom-nav.js'),
  'velin-carousel': () => import('../velin-carousel.js'),
  'velin-code-block': () => import('../velin-code-block.js'),
  'velin-collapse': () => import('../velin-collapse.js'),
  'velin-combobox': () => import('../velin-combobox.js'),
  'velin-command': () => import('../velin-command.js'),
  'velin-copy': () => import('../velin-copy.js'),
  'velin-countdown': () => import('../velin-countdown.js'),
  'velin-counter': () => import('../velin-counter.js'),
  'velin-dialog': () => import('../velin-dialog.js'),
  'velin-drawer': () => import('../velin-drawer.js'),
  'velin-dropdown': () => import('../velin-dropdown.js'),
  'velin-email': () => import('../velin-email.js'),
  'velin-icon': () => import('../velin-icon.js'),
  'velin-lightbox': () => import('../velin-lightbox.js'),
  'velin-live-dot': () => import('../velin-live-dot.js'),
  'velin-menubar': () => import('../velin-menubar.js'),
  'velin-modal': () => import('../velin-modal.js'),
  'velin-persist': () => import('../velin-persist.js'),
  'velin-popover': () => import('../velin-popover.js'),
  'velin-progress-ring': () => import('../velin-progress-ring.js'),
  'velin-rating': () => import('../velin-rating.js'),
  'velin-scroll-top': () => import('../velin-scroll-top.js'),
  'velin-scrollspy': () => import('../velin-scrollspy.js'),
  'velin-search': () => import('../velin-search.js'),
  'velin-secure-field': () => import('../velin-secure-field.js'),
  'velin-segmented-control': () => import('../velin-segmented-control.js'),
  'velin-sheet': () => import('../velin-sheet.js'),
  'velin-sparkline': () => import('../velin-sparkline.js'),
  'velin-stepper': () => import('../velin-stepper.js'),
  'velin-stepper-wc': () => import('../velin-stepper.js'),
  'velin-tabs': () => import('../velin-tabs.js'),
  'velin-theme-toggle': () => import('../velin-theme-toggle.js'),
  'velin-toast': () => import('../velin-toast.js'),
  'velin-tooltip': () => import('../velin-tooltip.js'),
  'velin-tooltip-wc': () => import('../velin-tooltip.js'),
};
